[tool.ruff]
target-version = "py310"
cache-dir = ".cache/ruff"
src = ["src"]
line-length = 120
show-fixes = true

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = [
    "YTT",    # flake8-2020
    "ASYNC",  # flake8-async
    "S1",     # flake8-bandit
    "BLE",    # flake8-blind-except
    "FBT",    # flake8-boolean-trap
    "B",      # flake8-bugbear
    "COM818", # flake8-commas
    "C4",     # flake8-comprehensions
    "EXE",    # flake8-executable
    "INT",    # flake8-gettext
    "ISC",    # flake8-implicit-str-concat
    "ICN",    # flake8-import-conventions
    "LOG",    # flake8-logging
    "G",      # flake8-logging-format
    "PIE",    # flake8-pie
    "PT",     # flake8-pytest-style
    "RSE",    # flake8-raise
    "SIM",    # flake8-simplify
    "SLOT",   # flake8-slots
    "TID",    # flake8-tidy-imports
    "TCH",    # flake8-type-checking
    "FLY",    # flynt
    "I",      # isort
    "C90",    # mccabe
    "N",      # pep8-naming
    "E",      # pycodestyle error
    "W",      # pycodestyle warning
    "D2",     # pydocstyle
    "D3",     # pydocstyle
    "D4",     # pydocstyle
    "F",      # pyflakes
    "PGH",    # pygrep-hooks
    "PLE",    # pylint error
    "PLW",    # pylint warning
    "UP",     # pyupgrade
    "RUF",
]
ignore = [
    # Use of assert detected
    "S101",
    # Use a single if statement instead of nested if statements
    "SIM102",
    # Use ternary operator {contents} instead of if-else-block
    "SIM108",
    # Exception name {name} should be named with an Error suffix
    "N818",
    # Line too long ({width} > {limit})
    "E501",
]

[tool.ruff.lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.mypy]
python_version = "3.10"
cache_dir = ".cache/mypy"
ignore_missing_imports = true
disallow_untyped_defs = true
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
show_error_context = true
show_column_numbers = true
pretty = true

[tool.pyright]
pythonVersion = "3.10"
pythonPlatform = "All"
typeCheckingMode = "standard"
strictListInference = true
strictDictionaryInference = true
strictSetInference = true
